# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-17 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_created_initial_anxiety_score_card_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='anxietyscorecard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
