# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-01 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_anxiety-score-card-model-add-time-periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 1, 19, 40, 13, 513214, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 1, 19, 40, 27, 880441, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
