# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_moved-score-choices-to-anxiety-score-card-model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anxietyscore',
            name='task',
        ),
        migrations.DeleteModel(
            name='AnxietyScore',
        ),
    ]
