# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_removed-anxiety-score-model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_0_min',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_10_min',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_15_min',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_30_min',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_5_min',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_60_min',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
    ]
