# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_removed-anxiety-score-model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_0_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_10_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_15_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_30_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_5_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_60_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
    ]
