# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocdactionuser',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
