# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_ocdactionuser_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocdactionuser',
            name='have_ocd',
            field=models.BooleanField(default=True),
        ),
    ]
