# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-01 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
