# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-02 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='taskname',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='username',
        ),
    ]
