# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-02 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170102_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='user',
        ),
    ]
