# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_tasks_into_separate_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocdactionuser',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='ocdactionuser',
            name='username',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
