# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20170219_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocdactionuser',
            old_name='username',
            new_name='nickname',
        ),
    ]
