# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_anxiety-score-card-model-allow-null-scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_10_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_10', to='challenges.AnxietyScore'),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_15_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_15', to='challenges.AnxietyScore'),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_20_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_20', to='challenges.AnxietyScore'),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='score_after_5_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_5', to='challenges.AnxietyScore'),
        ),
    ]
