# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_anxiety-score-card-model-allow-blank-scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anxietyscore',
            name='user',
        ),
    ]
