# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_added-created-and-updated-fields-to-task-model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_0_min',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_10_min',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_15_min',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_30_min',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_5_min',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_60_min',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2),
            preserve_default=False,
        ),
    ]
