# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_updated-names-of-the-score-choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_0_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_10_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_15_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_30_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_5_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_60_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
    ]
