# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_auto_20170812_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='anxietyscorecard',
            name='anxiety_at_120_min',
            field=models.CharField(choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_10_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_15_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_30_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_5_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='anxiety_at_60_min',
            field=models.CharField(blank=True, choices=[('0', 'zero'), ('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=2),
        ),
    ]
