# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_alter_anxiety_score_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
