# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_updated_anxiety_score_card_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
