# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-13 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_updated_anxiety_score_card_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Challenge',
            old_name='challenge_compulsions',
            new_name='compulsion',
        ),
        migrations.RenameField(
            model_name='Challenge',
            old_name='challenge_fears',
            new_name='exposure',
        ),
        migrations.RenameField(
            model_name='Challenge',
            old_name='challenge_goals',
            new_name='obsession',
        ),
    ]
