# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-10 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_challenge_anxietyscore_onetoone_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_0_min',
            new_name='anxiety_at_0_min',
        ),
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_10_min',
            new_name='anxiety_at_10_min',
        ),
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_120_min',
            new_name='anxiety_at_120_min',
        ),
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_15_min',
            new_name='anxiety_at_15_min',
        ),
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_30_min',
            new_name='anxiety_at_30_min',
        ),
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_5_min',
            new_name='anxiety_at_5_min',
        ),
        migrations.RenameField(
            model_name='anxietyscorecard',
            old_name='score_after_60_min',
            new_name='anxiety_at_60_min',
        ),
    ]
