# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-13 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_challenge_in_progress'),
        ('challenges', '0019_rename_fields_in_challenges'),
    ]

    operations = [
    ]
