# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0021_auto_20180204_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='anxietyscorecard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
