# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-03 20:08
from __future__ import unicode_literals

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Challenge = apps.get_model('challenges', 'Challenge')
    for row in Challenge.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    AnxietyScoreCard = apps.get_model('challenges', 'AnxietyScoreCard')
    for row in AnxietyScoreCard.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0022_auto_20180803_2007'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
