# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0023_auto_20180803_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anxietyscorecard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
