# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_auto_20180803_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='anxietyscorecard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anxietyscorecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
